// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:             db,
		Activity:       newActivity(db, opts...),
		Post:           newPost(db, opts...),
		Project:        newProject(db, opts...),
		SqliteSequence: newSqliteSequence(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	Activity       activity
	Post           post
	Project        project
	SqliteSequence sqliteSequence
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Activity:       q.Activity.clone(db),
		Post:           q.Post.clone(db),
		Project:        q.Project.clone(db),
		SqliteSequence: q.SqliteSequence.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:             db,
		Activity:       q.Activity.replaceDB(db),
		Post:           q.Post.replaceDB(db),
		Project:        q.Project.replaceDB(db),
		SqliteSequence: q.SqliteSequence.replaceDB(db),
	}
}

type queryCtx struct {
	Activity       *activityDo
	Post           *postDo
	Project        *projectDo
	SqliteSequence *sqliteSequenceDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		Activity:       q.Activity.WithContext(ctx),
		Post:           q.Post.WithContext(ctx),
		Project:        q.Project.WithContext(ctx),
		SqliteSequence: q.SqliteSequence.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
