// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"gorm.io/gen/examples/dal/model"
)

func newTwoFa(db *gorm.DB, opts ...gen.DOOption) twoFa {
	_twoFa := twoFa{}

	_twoFa.twoFaDo.UseDB(db, opts...)
	_twoFa.twoFaDo.UseModel(&model.TwoFa{})

	tableName := _twoFa.twoFaDo.TableName()
	_twoFa.ALL = field.NewAsterisk(tableName)
	_twoFa.ID = field.NewInt32(tableName, "id")
	_twoFa.CreatedAt = field.NewTime(tableName, "created_at")
	_twoFa.UpdatedAt = field.NewTime(tableName, "updated_at")
	_twoFa.DeletedAt = field.NewField(tableName, "deleted_at")
	_twoFa.KeyMain = field.NewString(tableName, "key_main")
	_twoFa.KeyBackup = field.NewString(tableName, "key_backup")
	_twoFa.UUIDSha = field.NewString(tableName, "uuid_sha")
	_twoFa.UUIDEnc = field.NewString(tableName, "uuid_enc")
	_twoFa.Status = field.NewString(tableName, "status")
	_twoFa.IDAuth = field.NewInt32(tableName, "id_auth")

	_twoFa.fillFieldMap()

	return _twoFa
}

type twoFa struct {
	twoFaDo twoFaDo

	ALL       field.Asterisk
	ID        field.Int32
	CreatedAt field.Time
	UpdatedAt field.Time
	DeletedAt field.Field
	KeyMain   field.String
	KeyBackup field.String
	UUIDSha   field.String
	UUIDEnc   field.String
	Status    field.String
	IDAuth    field.Int32

	fieldMap map[string]field.Expr
}

func (t twoFa) Table(newTableName string) *twoFa {
	t.twoFaDo.UseTable(newTableName)
	return t.updateTableName(newTableName)
}

func (t twoFa) As(alias string) *twoFa {
	t.twoFaDo.DO = *(t.twoFaDo.As(alias).(*gen.DO))
	return t.updateTableName(alias)
}

func (t *twoFa) updateTableName(table string) *twoFa {
	t.ALL = field.NewAsterisk(table)
	t.ID = field.NewInt32(table, "id")
	t.CreatedAt = field.NewTime(table, "created_at")
	t.UpdatedAt = field.NewTime(table, "updated_at")
	t.DeletedAt = field.NewField(table, "deleted_at")
	t.KeyMain = field.NewString(table, "key_main")
	t.KeyBackup = field.NewString(table, "key_backup")
	t.UUIDSha = field.NewString(table, "uuid_sha")
	t.UUIDEnc = field.NewString(table, "uuid_enc")
	t.Status = field.NewString(table, "status")
	t.IDAuth = field.NewInt32(table, "id_auth")

	t.fillFieldMap()

	return t
}

func (t *twoFa) WithContext(ctx context.Context) *twoFaDo { return t.twoFaDo.WithContext(ctx) }

func (t twoFa) TableName() string { return t.twoFaDo.TableName() }

func (t twoFa) Alias() string { return t.twoFaDo.Alias() }

func (t *twoFa) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := t.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (t *twoFa) fillFieldMap() {
	t.fieldMap = make(map[string]field.Expr, 10)
	t.fieldMap["id"] = t.ID
	t.fieldMap["created_at"] = t.CreatedAt
	t.fieldMap["updated_at"] = t.UpdatedAt
	t.fieldMap["deleted_at"] = t.DeletedAt
	t.fieldMap["key_main"] = t.KeyMain
	t.fieldMap["key_backup"] = t.KeyBackup
	t.fieldMap["uuid_sha"] = t.UUIDSha
	t.fieldMap["uuid_enc"] = t.UUIDEnc
	t.fieldMap["status"] = t.Status
	t.fieldMap["id_auth"] = t.IDAuth
}

func (t twoFa) clone(db *gorm.DB) twoFa {
	t.twoFaDo.ReplaceConnPool(db.Statement.ConnPool)
	return t
}

func (t twoFa) replaceDB(db *gorm.DB) twoFa {
	t.twoFaDo.ReplaceDB(db)
	return t
}

type twoFaDo struct{ gen.DO }

func (t twoFaDo) Debug() *twoFaDo {
	return t.withDO(t.DO.Debug())
}

func (t twoFaDo) WithContext(ctx context.Context) *twoFaDo {
	return t.withDO(t.DO.WithContext(ctx))
}

func (t twoFaDo) ReadDB() *twoFaDo {
	return t.Clauses(dbresolver.Read)
}

func (t twoFaDo) WriteDB() *twoFaDo {
	return t.Clauses(dbresolver.Write)
}

func (t twoFaDo) Session(config *gorm.Session) *twoFaDo {
	return t.withDO(t.DO.Session(config))
}

func (t twoFaDo) Clauses(conds ...clause.Expression) *twoFaDo {
	return t.withDO(t.DO.Clauses(conds...))
}

func (t twoFaDo) Returning(value interface{}, columns ...string) *twoFaDo {
	return t.withDO(t.DO.Returning(value, columns...))
}

func (t twoFaDo) Not(conds ...gen.Condition) *twoFaDo {
	return t.withDO(t.DO.Not(conds...))
}

func (t twoFaDo) Or(conds ...gen.Condition) *twoFaDo {
	return t.withDO(t.DO.Or(conds...))
}

func (t twoFaDo) Select(conds ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Select(conds...))
}

func (t twoFaDo) Where(conds ...gen.Condition) *twoFaDo {
	return t.withDO(t.DO.Where(conds...))
}

func (t twoFaDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *twoFaDo {
	return t.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (t twoFaDo) Order(conds ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Order(conds...))
}

func (t twoFaDo) Distinct(cols ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Distinct(cols...))
}

func (t twoFaDo) Omit(cols ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Omit(cols...))
}

func (t twoFaDo) Join(table schema.Tabler, on ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Join(table, on...))
}

func (t twoFaDo) LeftJoin(table schema.Tabler, on ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.LeftJoin(table, on...))
}

func (t twoFaDo) RightJoin(table schema.Tabler, on ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.RightJoin(table, on...))
}

func (t twoFaDo) Group(cols ...field.Expr) *twoFaDo {
	return t.withDO(t.DO.Group(cols...))
}

func (t twoFaDo) Having(conds ...gen.Condition) *twoFaDo {
	return t.withDO(t.DO.Having(conds...))
}

func (t twoFaDo) Limit(limit int) *twoFaDo {
	return t.withDO(t.DO.Limit(limit))
}

func (t twoFaDo) Offset(offset int) *twoFaDo {
	return t.withDO(t.DO.Offset(offset))
}

func (t twoFaDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *twoFaDo {
	return t.withDO(t.DO.Scopes(funcs...))
}

func (t twoFaDo) Unscoped() *twoFaDo {
	return t.withDO(t.DO.Unscoped())
}

func (t twoFaDo) Create(values ...*model.TwoFa) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Create(values)
}

func (t twoFaDo) CreateInBatches(values []*model.TwoFa, batchSize int) error {
	return t.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (t twoFaDo) Save(values ...*model.TwoFa) error {
	if len(values) == 0 {
		return nil
	}
	return t.DO.Save(values)
}

func (t twoFaDo) First() (*model.TwoFa, error) {
	if result, err := t.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.TwoFa), nil
	}
}

func (t twoFaDo) Take() (*model.TwoFa, error) {
	if result, err := t.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.TwoFa), nil
	}
}

func (t twoFaDo) Last() (*model.TwoFa, error) {
	if result, err := t.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.TwoFa), nil
	}
}

func (t twoFaDo) Find() ([]*model.TwoFa, error) {
	result, err := t.DO.Find()
	return result.([]*model.TwoFa), err
}

func (t twoFaDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.TwoFa, err error) {
	buf := make([]*model.TwoFa, 0, batchSize)
	err = t.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (t twoFaDo) FindInBatches(result *[]*model.TwoFa, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return t.DO.FindInBatches(result, batchSize, fc)
}

func (t twoFaDo) Attrs(attrs ...field.AssignExpr) *twoFaDo {
	return t.withDO(t.DO.Attrs(attrs...))
}

func (t twoFaDo) Assign(attrs ...field.AssignExpr) *twoFaDo {
	return t.withDO(t.DO.Assign(attrs...))
}

func (t twoFaDo) Joins(fields ...field.RelationField) *twoFaDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Joins(_f))
	}
	return &t
}

func (t twoFaDo) Preload(fields ...field.RelationField) *twoFaDo {
	for _, _f := range fields {
		t = *t.withDO(t.DO.Preload(_f))
	}
	return &t
}

func (t twoFaDo) FirstOrInit() (*model.TwoFa, error) {
	if result, err := t.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.TwoFa), nil
	}
}

func (t twoFaDo) FirstOrCreate() (*model.TwoFa, error) {
	if result, err := t.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.TwoFa), nil
	}
}

func (t twoFaDo) FindByPage(offset int, limit int) (result []*model.TwoFa, count int64, err error) {
	result, err = t.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = t.Offset(-1).Limit(-1).Count()
	return
}

func (t twoFaDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = t.Count()
	if err != nil {
		return
	}

	err = t.Offset(offset).Limit(limit).Scan(result)
	return
}

func (t twoFaDo) Scan(result interface{}) (err error) {
	return t.DO.Scan(result)
}

func (t twoFaDo) Delete(models ...*model.TwoFa) (result gen.ResultInfo, err error) {
	return t.DO.Delete(models)
}

func (t *twoFaDo) withDO(do gen.Dao) *twoFaDo {
	t.DO = *do.(*gen.DO)
	return t
}
