// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameActivity = "Activity"

// Activity mapped from table <Activity>
type Activity struct {
	ID     int32  `gorm:"column:Id;not null" json:"Id"`
	Name   string `gorm:"column:Name;not null" json:"Name"`
	Active int32  `gorm:"column:Active;not null" json:"Active"`
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
