// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivity = "activity"

// Activity mapped from table <activity>
type Activity struct {
	ID          int32     `gorm:"column:id;not null" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Isactive    bool      `gorm:"column:isactive;not null" json:"isactive"`
	CreatedAt   time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Description string    `gorm:"column:description;not null" json:"description"`
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
