// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameAuth = "auths"

// Auth mapped from table <auths>
type Auth struct {
	AuthID      int32          `gorm:"column:auth_id;primaryKey" json:"auth_id"`
	CreatedAt   time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt   gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Email       string         `gorm:"column:email;not null" json:"email"`
	Password    string         `gorm:"column:password;not null" json:"password"`
	VerifyEmail int32          `gorm:"column:verify_email;not null" json:"verify_email"`
}

// TableName Auth's table name
func (*Auth) TableName() string {
	return TableNameAuth
}
