// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameCustomer = "customer"

// Customer mapped from table <customer>
type Customer struct {
	ID        int32          `gorm:"column:id;not null" json:"id"`
	Name      string         `gorm:"column:name;not null" json:"name"`
	Firstname string         `gorm:"column:firstname;not null" json:"firstname"`
	Lastname  string         `gorm:"column:lastname;not null" json:"lastname"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdateAt  time.Time      `gorm:"column:update_at;not null" json:"update_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
	Isactive  bool           `gorm:"column:isactive;not null" json:"isactive"`
}

// TableName Customer's table name
func (*Customer) TableName() string {
	return TableNameCustomer
}
