// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameExtratime = "extratime"

// Extratime mapped from table <extratime>
type Extratime struct {
	ID     int32   `gorm:"column:id;not null" json:"id"`
	Name   string  `gorm:"column:name;not null" json:"name"`
	Factor float64 `gorm:"column:factor;not null" json:"factor"`
}

// TableName Extratime's table name
func (*Extratime) TableName() string {
	return TableNameExtratime
}
