// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePicture = "picture"

// Picture mapped from table <picture>
type Picture struct {
	ID          int32  `gorm:"column:id;not null" json:"id"`
	Description string `gorm:"column:description;not null" json:"description"`
	Value       []byte `gorm:"column:value;not null" json:"value"`
	Post        int32  `gorm:"column:post;not null" json:"post"`
}

// TableName Picture's table name
func (*Picture) TableName() string {
	return TableNamePicture
}
