// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePost = "Post"

// Post mapped from table <Post>
type Post struct {
	ID        int32   `gorm:"column:Id;not null" json:"Id"`
	CreatedAt int32   `gorm:"column:CreatedAt;not null" json:"CreatedAt"`
	Comment   string  `gorm:"column:Comment;not null" json:"Comment"`
	Duration  float64 `gorm:"column:Duration;not null" json:"Duration"`
	Project   int32   `gorm:"column:Project;primaryKey" json:"Project"`
}

// TableName Post's table name
func (*Post) TableName() string {
	return TableNamePost
}
