// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectuser = "projectusers"

// Projectuser mapped from table <projectusers>
type Projectuser struct {
	ID        int32 `gorm:"column:id;not null" json:"id"`
	Project   int32 `gorm:"column:project;not null" json:"project"`
	Employee  int32 `gorm:"column:employee;not null" json:"employee"`
	Isgranted bool  `gorm:"column:isgranted;not null" json:"isgranted"`
}

// TableName Projectuser's table name
func (*Projectuser) TableName() string {
	return TableNameProjectuser
}
