// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProject = "Project"

// Project mapped from table <Project>
type Project struct {
	ID            int32  `gorm:"column:Id;not null" json:"Id"`
	Name          string `gorm:"column:Name;not null" json:"Name"`
	EstimateHours int32  `gorm:"column:EstimateHours;not null" json:"EstimateHours"`
}

// TableName Project's table name
func (*Project) TableName() string {
	return TableNameProject
}
