// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProjectactivity = "projectactivities"

// Projectactivity mapped from table <projectactivities>
type Projectactivity struct {
	ID       int32 `gorm:"column:id;not null" json:"id"`
	Project  int32 `gorm:"column:project;not null" json:"project"`
	Activity int32 `gorm:"column:activity;not null" json:"activity"`
}

// TableName Projectactivity's table name
func (*Projectactivity) TableName() string {
	return TableNameProjectactivity
}
