// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameStatus = "status"

// Status mapped from table <status>
type Status struct {
	ID       int32  `gorm:"column:id;not null" json:"id"`
	Name     string `gorm:"column:name;not null" json:"name"`
	Isactive bool   `gorm:"column:isactive;not null" json:"isactive"`
}

// TableName Status's table name
func (*Status) TableName() string {
	return TableNameStatus
}
