// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameTwoFa = "two_fas"

// TwoFa mapped from table <two_fas>
type TwoFa struct {
	ID        int32          `gorm:"column:id;primaryKey" json:"id"`
	CreatedAt time.Time      `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt time.Time      `gorm:"column:updated_at;not null" json:"updated_at"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;not null" json:"deleted_at"`
	KeyMain   string         `gorm:"column:key_main;not null" json:"key_main"`
	KeyBackup string         `gorm:"column:key_backup;not null" json:"key_backup"`
	UUIDSha   string         `gorm:"column:uuid_sha;not null" json:"uuid_sha"`
	UUIDEnc   string         `gorm:"column:uuid_enc;not null" json:"uuid_enc"`
	Status    string         `gorm:"column:status;not null" json:"status"`
	IDAuth    int32          `gorm:"column:id_auth;not null" json:"id_auth"`
}

// TableName TwoFa's table name
func (*TwoFa) TableName() string {
	return TableNameTwoFa
}
